SocialGouv/pass_emploi_app

lib/models/user_action.dart, lib/presentation/home_item.dart, lib/presentation/home_page_view_model.dart, lib/presentation/user_action_item.dart, lib/presentation/user_action_page_view_model.dart, lib/presentation/user_action_view_model.dart, lib/redux/reducers/ui_action_reducer.dart, lib/widgets/user_action_card.dart, lib/widgets/user_action_widget.dart, pubspec.lock, test/assets/home.json, test/models/home_test.dart, test/presentation/home_page_view_model_test.dart
=> Feat: adding comment in app

lib/models/offre_emploi.dart, lib/repositories/offre_emploi_repository.dart, test/assets/offres_emploi.json
Suite à [cette PR back](https://github.com/SocialGouv/pass-emploi-api/pull/65)
=> [TECH] Liste des offres - update modèle json  

lib/pages/offre_emploi_search_page.dart, lib/presentation/user_action_details_view_model.dart, lib/presentation/user_action_view_model.dart, lib/redux/actions/user_action_actions.dart, lib/redux/middlewares/user_action_middleware.dart, lib/redux/reducers/ui_action_reducer.dart, lib/redux/reducers/user_action_reducer.dart, lib/redux/states/app_state.dart, lib/redux/states/user_action_delete_state.dart, lib/repositories/user_action_repository.dart, lib/ui/app_colors.dart, lib/ui/strings.dart, lib/widgets/bottom_sheets.dart, lib/widgets/button.dart, lib/widgets/user_action_create_bottom_sheet.dart, lib/widgets/user_action_details_bottom_sheet.dart, test/doubles/stubs.dart, test/feature/user_action_delete_test.dart, test/presentation/user_action_details_view_model_test.dart, test/presentation/user_action_view_model_test.dart, test/redux/middlewares/user_action_middleware_test.dart
[Trello](https://trello.com/c/FVOCvEQd/70)
=> [FEATURE] 70 : K peut supprimer une action qu'il a ajoutée

lib/widgets/user_action_details_bottom_sheet.dart
Petit fail de ma part, ma condition pour afficher la snackbar était foireuse
=> [COPO] 70 - Ne pas afficher la snackbar si on maj le statut

lib/pages/offre_emploi_details_page.dart, lib/ui/strings.dart, lib/ui/text_styles.dart
What's new:
- add required icon to required skills
- add hoop info on required icon tap
- add url redirection to company site
=> feat: US-98 detailed offer required icon

lib/widgets/chat_message_widget.dart, lib/widgets/text_with_clickable_links.dart
[Le trello](https://trello.com/c/MPvcwFO8/169-us-169-k-peut-cliquer-sur-les-liens-pr%C3%A9sents-dans-le-chat)
Merci linkify, ça aurait été vraiment galère sinon 😇
=> [FEAT] : 169 - K peut cliquer sur les liens présents dans le chat

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/xml/backup_rules.xml, lib/auth/auth_access_token_retriever.dart, lib/auth/authenticator.dart, lib/main.dart, lib/redux/middlewares/login_middleware.dart, pubspec.lock, pubspec.yaml, test/auth/auth_access_token_retriever_test.dart, test/auth/authenticator_test.dart, test/doubles/spies.dart, test/doubles/stubs.dart
Un truc particulier : J'ai spécifié qu'il ne fallait pas auto-backuper le fichier de shared pref dans lequel sont stockés les tokens car [ça pose problème avec la lib](https://github.com/mogol/flutter_secure_storage/issues/43), et j'ai l'impression que c'est plutôt sain tfaçons. 
A noter, je n'ai pas réussi à tester sur iOS - j'ai des problèmes de build 😢
=> [Tech] 181 - tokens in secured storage

CONTRIBUTING.md, README.md
Aller voir directement le [rendu ici](https://github.com/SocialGouv/pass_emploi_app/blob/docs/204-doc-initier-le-contributingmd-du-projet-flutter/CONTRIBUTING.md)
=> [DOC] Initialisation du fichier CONTRIBUTING.md

lib/configuration/configuration.dart, lib/crashlytics/crashlytics.dart, lib/main.dart, lib/push/firebase_push_notification_manager.dart, lib/repositories/chat_repository.dart, lib/repositories/firebase_auth_repository.dart, lib/repositories/immersion_details_repository.dart, lib/repositories/immersion_repository.dart, lib/repositories/offre_emploi_details_repository.dart, lib/repositories/offre_emploi_favoris_repository.dart, lib/repositories/offre_emploi_repository.dart, lib/repositories/register_token_repository.dart, lib/repositories/rendezvous_repository.dart, lib/repositories/search_location_repository.dart, lib/repositories/user_action_repository.dart, test/doubles/dummies.dart
Dans le temps imparti, Crashlytics est la solution la plus pragmatique. Voir plus tard si on ne remonte pas ça dans ELK directement, pour centraliser tous nos logs.
=> [CHORE]  210 - Remonter les exceptions lors des appels API à Firebase

lib/configuration/configuration.dart, lib/main.dart, lib/pages/force_update_page.dart, lib/presentation/force_update_view_model.dart, lib/ui/strings.dart, test/doubles/fixtures.dart, test/presentation/force_update_view_model_test.dart
Je vous ai mis [des vidéos ici avec le rendu](https://drive.google.com/drive/folders/1E7I6s34gey_t7cFfRljBU26NYGFHGV4A?usp=sharing).
Sur iOS en prod, c'est normal que le lien de la fiche de l'app soit cassé, car l'app n'est pas encore publiée.
=> [CHORE] 212 - Ajout des boutons de redirection sur la page de forçage de la mise à jour de l'app

lib/pages/offre_emploi_list_page.dart, lib/presentation/offre_emploi_search_results_view_model.dart, lib/redux/reducers/offre_emploi_reducer.dart, scripts/prod_release_when_github_is_down.sh, test/feature/offre_emploi_filtres_test.dart, test/presentation/offre_emploi_search_results_view_model_test.dart
Reset des filtres si jamais on a une erreur
Ajout d'un message sur la liste si jamais l'utilisateur appuie sur le bouton back de l'app bar.
=> [COPO] 119 - Fix du comportement en cas erreur

lib/configuration/app_version_checker.dart, test/configuration/app_version_checker_test.dart
Permet d'afficher la page de force update sur staging
=> [TECH] Gestion du suffixe "-staging" dans le check de la version

lib/auth/authenticator.dart, lib/main.dart, lib/pages/login_page.dart, lib/presentation/login_view_model.dart, lib/redux/actions/login_actions.dart, lib/redux/middlewares/login_middleware.dart, lib/redux/reducers/login_action_reducer.dart, lib/redux/states/app_state.dart, lib/redux/states/configuration_state.dart, lib/ui/strings.dart, test/auth/authenticator_test.dart, test/doubles/fixtures.dart, test/doubles/spies.dart, test/doubles/stubs.dart, test/feature/login_test.dart, test/presentation/login_view_model_test.dart
[Le trello](https://trello.com/c/L6ctQZzD/222-k-peut-se-connecter-avec-ses-identifiants-pe)
A noter : 
- C'est pas vraiment testable fonctionnellement pour l'instant car le `kc_idp_hint` de PE jeune n'est pas encore pris en compte par keycloack. On a donc pour l'instant zéro diff entre l'authent PE et l'authent générique.
=> [FEAT] 222 - K peut se connecter avec ses identifiants Pôle Emploi

lib/analytics/analytics_constants.dart, lib/pages/offre_emploi_details_page.dart, lib/pages/offre_emploi_filtres_page.dart, lib/pages/offre_emploi_list_page.dart, lib/pages/offre_emploi_search_page.dart, lib/pages/search_annonces_page.dart, lib/presentation/offre_emploi_filtres_view_model.dart, lib/presentation/offre_emploi_search_results_view_model.dart, lib/presentation/offre_emploi_search_view_model.dart, lib/redux/actions/offre_emploi_actions.dart, lib/redux/middlewares/offre_emploi_middleware.dart, lib/redux/reducers/offre_emploi_reducer.dart, lib/redux/states/offre_emploi_search_parameters_state.dart, lib/repositories/offre_emploi_repository.dart, lib/ui/strings.dart, test/doubles/stubs.dart, test/feature/offre_emploi_filtres_test.dart, test/feature/offre_emploi_list_test.dart, test/feature/offre_emploi_search_test.dart, test/presentation/offre_emploi_filtres_view_model_test.dart, test/presentation/offre_emploi_search_results_view_model_test.dart, test/presentation/offre_emploi_search_view_model_test.dart, test/repositories/offre_emploi_repository_test.dart
[Lien vers le Trello.](https://trello.com/c/m5S83qYf/201-k-peut-faire-une-recherche-doffres-en-alternance)
=> [FEAT] 201 - K peut faire une recherche d'offres en alternance

lib/pages/offre_emploi_details_page.dart, lib/pages/user_action_list_page.dart, lib/presentation/user_action_list_page_view_model.dart, lib/presentation/user_action_view_model.dart, lib/redux/reducers/user_action_reducer.dart, lib/ui/strings.dart, lib/widgets/immersion_tags.dart, lib/widgets/offre_emploi_list_item.dart, lib/widgets/tags.dart, lib/widgets/user_action_list_item.dart, test/feature/user_action_update_test.dart, test/presentation/user_action_list_page_view_model_test.dart, test/presentation/user_action_view_model_test.dart
[Le trello](https://trello.com/c/lcZZud6e/221-k-voit-ses-actions-tri%C3%A9es-par-date-de-modification-et-statut)
=> [FEAT] 221 - K voit ses actions triées par date de modification et statut

lib/analytics/analytics_constants.dart, lib/models/offre_emploi.dart, lib/network/post_offre_emploi_favori.dart, lib/pages/app_page.dart, lib/pages/favoris_page.dart, lib/pages/favoris_tabs_page.dart, lib/pages/main_page.dart, lib/pages/offre_emploi_details_page.dart, lib/pages/offre_emploi_filtres_page.dart, lib/pages/offre_emploi_list_page.dart, lib/pages/offre_emploi_search_page.dart, lib/pages/offre_page.dart, lib/presentation/offre_emploi_favoris_list_view_model.dart, lib/presentation/offre_emploi_item_view_model.dart, lib/presentation/offre_emploi_search_results_view_model.dart, lib/repositories/offre_emploi_favoris_repository.dart, lib/widgets/favori_heart.dart, lib/widgets/offre_emploi_list_item.dart, test/assets/offre_emploi_favoris_data.json, test/doubles/fixtures.dart, test/feature/offre_emploi_favoris_test.dart, test/presentation/offre_emploi_favoris_list_view_model_test.dart, test/presentation/offre_emploi_search_results_view_model_test.dart, test/repositories/offre_emploi_favoris_repository_test.dart, test/repositories/offre_emploi_repository_test.dart, test/widgets/favori_heart_test.dart
Désolé pour la grosse MR qui inclue 2 US…
On a perdu plus d'une heure avec Maxime a essayé de centrer les messages d'erreurs, loader et retry dans la nouvelle page avec des boutons. C'est plus difficile qu'il n'y parait 🤪. J'ai mis une pauvre marge pour arrêter de perdre du temps (et c'est pas faute d'avoir essayé…)
=> [FEAT] 217 -218 : ajout des favoris sur l alternance

lib/models/offre_emploi.dart, lib/pages/offre_emploi_list_page.dart, test/assets/offre_emploi_favoris_data.json, test/assets/offres_emploi.json, test/repositories/offre_emploi_favoris_repository_test.dart, test/repositories/offre_emploi_repository_test.dart
[Ticket 1](https://trello.com/c/ly7zRm48/244) 
[Ticket 2](https://trello.com/c/4nbpKhDx/245)
=> [FIXES] Chargement plus d'offres & Favori avec localisation vide

lib/pages/boite_a_outils_page.dart
[Le trello](https://trello.com/c/vACmuXDU/230-tagger-le-clic-sur-liens-sortants-de-la-boite-%C3%A0-outils)
=> [FEAT] 230 - Tagger le clic sur liens sortants de la boite à outils

lib/network/post_tracking_event_request.dart, lib/pages/chat_page.dart, lib/pages/immersion_details_page.dart, lib/pages/offre_emploi_details_page.dart, lib/presentation/call_to_action.dart, lib/presentation/immersion_details_view_model.dart, lib/repositories/tracking_analytics/tracking_event_repository.dart, lib/utils/context_extensions.dart, test/doubles/dummies.dart, test/presentation/immersion_details_view_model_test.dart, test/repositories/tracking_event_repository_test.dart
[Le trello](https://trello.com/c/HZLRZpwc/224-app-rattrapage-%C3%A9v%C3%A8nement-dengagement-solutions) 
(avec en bonus les events offre d'emploi / d'alternance affichées)
Rien de bien spécial, mise à part sur le dernier commit, j'ai utilisé une extension sur `BuildContext` pour simplifier les appels au tracking. Je veux bien votre avis dessus ! :)
=> [FEAT] 224 - Rattrapage évènement d'engagement solutions

lib/push/firebase_push_notification_manager.dart, lib/redux/middlewares/login_middleware.dart, lib/repositories/chat_repository.dart, pubspec.yaml
Report de ce qui avait été fait sur master sur develop
--> revert de la pr firebase pour fixer le chat sur iOS
--> bump de la version
=> [REPORT] Release firebase ios fix and 1.1.1 version bump

lib/redux/middlewares/chat_initializer_middleware.dart, lib/redux/middlewares/login_middleware.dart, lib/redux/store/store_factory.dart, test/doubles/dummies.dart, test/doubles/stubs.dart, test/feature/chat_test.dart, test/feature/post_login_test.dart
[Lien vers le Trello](https://trello.com/c/MlGQzt0V/299-le-chat-est-vide-au-clic-sur-la-notification-de-nouveau-message)
=> [FIX] 299 - Le chat est vide au clic sur la notification de nouveau message

lib/presentation/rendezvous_list_page_view_model.dart, test/presentation/rendezvous_list_page_view_model_test.dart
[Le trello](https://trello.com/c/cygyLGbk/340-am%C3%A9liorations-liste-des-rdv-jeune)
=> [FEATURE] 340 - Améliorations liste des RDV jeune

lib/analytics/analytics_constants.dart, lib/auth/auth_id_token.dart, lib/models/user.dart, lib/pages/login_page.dart, lib/pages/main_page.dart, lib/pages/profil_page.dart, lib/presentation/profil_page_view_model.dart, lib/redux/middlewares/login_middleware.dart, lib/ui/strings.dart, lib/ui/text_styles.dart, lib/widgets/cards/boite_a_outils_card.dart, lib/widgets/cards/profil_card.dart, lib/widgets/label_value_row.dart, lib/widgets/secondary_button.dart, test/auth/auth_access_token_retriever_test.dart, test/auth/auth_id_token_test.dart, test/auth/authenticator_test.dart, test/doubles/fixtures.dart, test/doubles/stubs.dart, test/feature/login_test.dart, test/presentation/profil_page_view_model_test.dart, test/redux/middlewares/create_user_action_middleware_test.dart, test/redux/middlewares/register_push_notification_token_middleware_test.dart
[Le trello](https://trello.com/c/Wtx7Nf6w/328-k-a-acc%C3%A8s-%C3%A0-son-profil-et-aux-pages-l%C3%A9gales-depuis-le-profil)
Comme vu ensemble, il faudra juste changer les liens une fois qu'on aura les bons
=> [FEATURE] 328 - K a accès à son profil et aux pages légales depuis le profil

lib/analytics/analytics_constants.dart, lib/main.dart, lib/redux/middlewares/user_tracking_structure_middleware.dart, lib/redux/store/store_factory.dart, pubspec.lock, pubspec.yaml
Je vous propose de partir sur la dépendance forkée pour l'instant pour ne pas bloquer le ticket trop longtemps.
On verra après si la [PR sur le repo dart-matomo](https://github.com/poitch/dart-matomo/pull/38) est mergée, on pourra repointer dessus.
=> [FEATURE] 331 - Analytics segmentés PE/ML

lib/widgets/cards/boite_a_outils_card.dart
Parce qu'il fallait bien le faire un moment ;)
=> [FIX] Correction du ripple rectangulaire sur les cartes de la boite à outils

lib/ui/text_styles.dart, lib/widgets/bottom_sheets/user_action_details_bottom_sheet.dart, lib/widgets/buttons/filtre_button.dart, lib/widgets/buttons/primary_action_button.dart
C'était une histoire de TextStyle plus utilisé. Par contre, j'ai été surpris de voir que la taille de la fonte du Primary était de 14, alors que sur [ZeroHeight](https://zeroheight.com/2f9442f46/p/297f4f--button/b/94db9a/i/82026461), elle est indiquée à 16.
Du coup, j'ai mis à jour le style, mais ça va augmenter la taille de tous les boutons dans l'app… A voir si c'est le bon choix, ou alors si je laisse à 14, et je ne mets à 16 que dans les 3/4 cas où c'était fait à la main.
=> [FIX] 354 - Le bouton "supprimer" pour une action n'est plus visible

lib/models/offre_emploi_details.dart, lib/models/rendezvous.dart, lib/models/service_civique.dart, lib/models/service_civique/service_civique_detail.dart, lib/models/user_action.dart, lib/utils/string_extensions.dart, test/assets/home.json, test/assets/service_civique_detail.json, test/doubles/fixtures.dart, test/models/user_action_test.dart, test/repositories/rendezvous_repository_test.dart, test/utils/test_datetime.dart
J'en ai profité pour poser un TU sur le `RendezvousRepository`.
La solution pour les tests est pas folle, mais dure de faire mieux dans le temps de ce hotfix.
Pour info, si ça vous va on merge sur develop et on fait un PO review normale. 
Ensuite on cherry-pickera sur le tag 1.2.0
=> [FIX] 411 - Affichage des rendez vous suivant la locale du téléphone pour bien afficher les horaires dans les territoires hors france metropolitaine

.github/workflows/continuous-integration-workflow.yml, .github/workflows/flutter_analysis.yml, .github/workflows/release-workflow.yml, pubspec.lock, pubspec.yaml
To run : 
`flutter upgrade`
`brew upgrade dart`
=> Tech: Upgrade dart & flutter versions

lib/repositories/immersion_details_repository.dart, lib/repositories/offre_emploi_details_repository.dart, lib/repositories/service_civique/service_civique_repository.dart, test/doubles/fixtures.dart, test/repositories/immersion_details_repository_test.dart, test/repositories/offre_emploi_details_repository_test.dart, test/repositories/service_civique/service_civique_deatils_repository_test.dart, test/repositories/service_civique/service_civique_test.dart
Trello -> https://trello.com/c/zGgdADQL/535-dans-mes-favoris-quand-une-offre-nest-plus-disponible-jai-un-message-derreur-au-lieu-de-la-page-doffre-plus-disponible
=> fix / US-535 Fix une régression d'affichage d'un offre favori indisponible 

ios/Runner.xcodeproj/project.pbxproj, lib/pages/user_action_list_page.dart, lib/presentation/user_action/user_action_list_page_view_model.dart, test/presentation/user_action/user_action_list_page_view_model_test.dart
Trello => https://trello.com/c/rpdpzW67/491-us-491-k-est-redirig%C3%A9-vers-le-d%C3%A9tail-de-son-action-quand-il-clique-sur-une-notification-action
Notion => https://www.notion.so/K-est-redirig-vers-le-d-tail-de-son-action-quand-il-clique-sur-une-notification-action-934189ce868c41b192e63d0f754dc09b
=> Feat/ [US-491] Redirection vers le détail de l'action depuis une notification

lib/pages/rendezvous/rendezvous_list_page.dart, lib/presentation/rendezvous/list/current_week_rendezvous_list_builder.dart, lib/presentation/rendezvous/list/future_months_rendezvous_list_builder.dart, lib/presentation/rendezvous/list/future_week_rendezvous_list_builder.dart, lib/presentation/rendezvous/list/past_rendezvous_list_builder.dart, lib/presentation/rendezvous/list/rendezvous_list_builder.dart, lib/presentation/rendezvous/list/rendezvous_list_view_model.dart, lib/ui/strings.dart, test/presentation/rendezvous/rendezvous_list_view_model_test.dart
Un peu de bruit inutile dans la MR car j'ai renommé pas mal de `RendezVous` en `Rendezvous`…
My bad
=> [FEAT] 563 - K peut accéder directement à son prochain rdv grâce à un bouton

lib/pages/mon_suivi_tabs_page.dart, lib/pages/user_action_list_page.dart
Notion -> https://www.notion.so/Animation-pour-masquer-le-header-sur-Actions-et-rdv-cd708f9524b741988c2dae3bb76efa19
Trello -> https://trello.com/c/8TQ62iPR/564-us-564-animation-pour-masquer-le-header-sur-actions-et-rendez-vous
=> Feat/ US-564 Animation pour masquer le header sur actions et rendez vous

lib/pages/offre_favoris_tab_page.dart, lib/pages/saved_search_tab_page.dart, lib/pages/search_annonces_page.dart
Trello => https://trello.com/c/cR4zrcay/596-mettre-le-service-civique-en-3%C3%A8me-position-dans-le-carrousel
Notion => https://www.notion.so/Mettre-le-service-civique-en-3-me-position-dans-le-carrousel-7ca6f25c94e04377b56d39ee75811a49
=> Feat / US-596 Mettre le service civique en 3ème position dans le carrousel

lib/widgets/dialogs/delete_user_dialog.dart
@lela-oc-to : en fait pas besoin de key ou autre => si tu devais re-set l'attribut à nul, c'est justement parce que ce n'était pas un attribut d'instance, et qu'en conséquence, sa valeur restait la même. Le fait de recréer une nouvelle instance de ton AlertDialog n'y changeais rien.
Dis-moi si ça te convient :)
=> [CHORE] 522 - Réduction de la portée de la variable globale pour la suppression de compte

lib/pages/immersion_filtres_page.dart, lib/pages/offre_emploi_filtres_page.dart, lib/pages/service_civique/service_civique_filtres_page.dart, lib/pages/service_civique/service_civique_list_page.dart, lib/widgets/buttons/filter_button.dart, lib/widgets/date_pickers/date_picker.dart, lib/widgets/sepline.dart, lib/widgets/slider/distance_slider.dart, lib/widgets/slider/slider_caption.dart, lib/widgets/slider/slider_value.dart, lib/widgets/toggles/date_toggle.dart, pubspec.lock
Trello => https://trello.com/c/mklhjrqY/594-us-594-fixer-le-bouton-filtrer-pour-quil-soit-toujours-visible
Notion => https://www.notion.so/Fixer-le-bouton-Filtrer-pour-qu-il-soit-toujours-visible-4e14923de03d41fb8e3af982dd2659d3
+ j'ai profité de ce ticket pour refactor les pages des filtres (offres, immersion et service civique)
+ j'ai update quelques libs pour que le projet build sur iOS
=> Feat / [US-594] Fixer le bouton "Filtrer" pour qu'il soit toujours visible

lib/presentation/user_action_pe/user_action_pe_view_model.dart, lib/ui/strings.dart, lib/utils/date_extensions.dart, lib/widgets/cards/user_action_pe_card.dart, test/presentation/user_action_pe/user_action_pe_view_model_test.dart
L'US n'est pas encore fini, il reste à supprimer le status "EN RETARD", j'attends le back pour finaliser, mais vous pouvez deja regarder le code.
TRELLO => https://trello.com/c/m7MXV0dS/642-us-642-app-afficher-le-statut-en-rouge-quand-la-t%C3%A2che-est-en-retard
Figma => https://www.figma.com/file/p5D0gUow1xIYmeYTUSQlSB/JRE---P%C3%B4le-Emploi?node-id=740%3A11162
=> Feat/US 642 Afficher le statut en rouge quand la tâche est en retard

lib/pages/force_update_page.dart, test/golden/force_update_page_golden_test.dart
J'en ai profité pour ajouter notre premier "quasi" test UI :) Merci ma nouvelle expérience sur le web !
=> [FIX] 705 - Le forçage de mise a jours de l'application amene a un ecran blanc

lib/features/user_action_pe/create/create_demarche_actions.dart, lib/features/user_action_pe/create/create_demarche_middleware.dart, lib/features/user_action_pe/create/create_demarche_reducer.dart, lib/features/user_action_pe/create/create_demarche_state.dart, lib/network/post_create_demarche.dart, lib/pages/actions/create_demarche_page.dart, lib/pages/actions/demarche_detail_page.dart, lib/presentation/user_action_pe/create_demarche_view_model.dart, lib/repositories/demarche/create_demarche_repository.dart, lib/ui/strings.dart, test/feature/user_action_pe/create_demarche_test.dart, test/presentation/user_action_pe/create_demarche_view_model_test.dart, test/repositories/demarche/create_demarche_repository_test.dart
Un peu de bruit sur le fichier `strings.dart`, car chez moi c'est bien formatté en 120 caractères par ligne, et non pas 80.
=> [RETOURS PO] 682 - K peut créer une démarche personnalisée

README.md
Déso pour le bruit de formattage, avec la dernière version d'Android Studio, ça marche enfin :)
=> [DOC] Process de hotfix

lib/features/chat/piece_jointe/piece_jointe_actions.dart, lib/features/chat/piece_jointe/piece_jointe_middleware.dart, lib/features/chat/piece_jointe/piece_jointe_reducer.dart, lib/features/chat/piece_jointe/piece_jointe_state.dart, lib/network/status_code.dart, lib/presentation/piece_jointe_view_model.dart, lib/repositories/piece_jointe_repository.dart, lib/ui/strings.dart, lib/widgets/chat/chat_piece_jointe_widget.dart, test/doubles/stubs.dart, test/dsl/app_state_dsl.dart, test/feature/chat/piece_jointe/piece_jointe_test.dart, test/presentation/chat/piece_jointe_view_model_test.dart
TRELLO => https://trello.com/c/ndHKCLmZ/680-us-680-k-voit-un-message-derreur-si-la-pj-nest-plus-disponible
Notion =>  https://www.notion.so/K-voit-un-message-d-erreur-si-la-PJ-n-est-plus-disponible-ebf431300994427a9a45a2f4ec724de3
Figma => https://www.figma.com/file/LYTcPpi6JipSRH3fP41YgF/Envoi-PJ-Conseiller?node-id=615%3A7080
=> Feat/ [US-680] K voit un message d’erreur si la PJ n’est plus disponible

lib/widgets/share_sheet.dart, pubspec.lock, pubspec.yaml
=> feat: 679 - download and share Piece Jointe

lib/analytics/analytics_constants.dart, lib/features/demarche/create/create_demarche_middleware.dart, lib/network/post_create_demarche.dart, lib/pages/demarche/create_demarche_personnalisee_page.dart, lib/pages/demarche/create_demarche_step3_page.dart, lib/presentation/demarche/create_demarche_step3_view_model.dart, lib/repositories/demarche/create_demarche_repository.dart, test/doubles/dummies.dart, test/feature/demarche/create_demarche_test.dart, test/presentation/demarche/create_demarche_step3_view_model_test.dart, test/repositories/demarche/create_demarche_repository_test.dart
La PR est sur la branche précédente pour faciliter sa lecture.
=> [FEAT] 726 - K peut compléter la démarche pré-renseigner et la créer

lib/models/message.dart, lib/models/offre_partagee.dart, lib/pages/offre_emploi_details_page.dart, lib/pages/partage_offre_page.dart, lib/presentation/chat_item.dart, lib/presentation/chat_page_view_model.dart, lib/presentation/partage_offre_page_view_model.dart, lib/repositories/chat_repository.dart, lib/ui/strings.dart, lib/widgets/chat/offre_message_widget.dart, test/models/message_test.dart, test/presentation/chat/chat_page_view_model_test.dart, test/presentation/partage_offre_page_view_model_test.dart
Trello => https://trello.com/c/du85OzEz/772-us-772-k-peut-cliquer-sur-le-lien-de-loffre-quil-a-envoy%C3%A9-dans-le-chat
Notion => https://www.notion.so/K-peut-cliquer-sur-le-lien-de-l-offre-qu-il-a-envoy-dans-le-chat-4f0129639e7f4858bef3532e45cc5738
Figma => https://www.figma.com/file/pXDGNOwut7qEMIqkz37j0q/Partage_offre_chat%F0%9F%98%BA?node-id=12%3A139
=> Feat/ US-772 K peut cliquer sur le lien de l’offre qu’il a envoyé dans le chat

lib/pages/demarche/demarche_detail_page.dart
Trello => https://trello.com/c/4Z1uvK2J/794-us-794-le-modificateur-dune-d%C3%A9marche-nest-pas-le-bon-il-semble-correspondre-au-cr%C3%A9ateur
=> bugfix: 794 - Le modificateur d'une démarche n'est pas le bon

lib/widgets/snack_bar/show_snack_bar.dart
Trello -> https://trello.com/c/U9vemVOT/765-us-765-faire-le-message-vert-de-confirmation-sur-lapp-sticky
=> Feat/ 765 - Faire le message vert de confirmation sur l'app sticky

lib/analytics/analytics_constants.dart, lib/features/rating/rating_actions.dart, lib/features/rating/rating_middleware.dart, lib/features/rating/rating_reducer.dart, lib/repositories/rating_repository.dart, lib/ui/strings.dart, lib/utils/mail_handler.dart, lib/widgets/bottom_sheets/rating_bottom_sheet.dart, lib/widgets/snack_bar/rating_snack_bar.dart, pubspec.yaml
Trello =>  https://trello.com/c/SbVvC5af/853-pousser-les-jeunes-%C3%A0-aller-noter-lapplication-avis-d%C3%A9favorable
Notion => https://www.notion.so/Pousser-les-jeunes-aller-noter-l-application-Avis-d-favorable-2cf9eebc886844b8bf6cea733eb747c7
Figma => https://www.figma.com/file/2Es4DIVoloizv0179GJdmy/Noter-l'app?node-id=479%3A1059
=> Feat/ US-853  Pousser les jeunes à aller noter l’application - Avis défavorable

assets/mode_demo/commentaires.json, lib/models/commentaire.dart, lib/pages/user_action/action_commentaires_page.dart, lib/pages/user_action/user_action_detail_page.dart, lib/presentation/user_action/user_action_details_view_model.dart, lib/ui/strings.dart, lib/widgets/comment.dart, test/assets/commentaires.json, test/doubles/fixtures.dart, test/feature/user_action/commentaire/action_commentaire_list_test.dart, test/repositories/action_commentaire_repository_test.dart
Trello => https://trello.com/c/Aq6twROB/890-us-890-app-afficher-les-commentaires-dune-action
Notion => https://www.notion.so/APP-Afficher-les-commentaires-d-une-action-d4403657220b4f74a98f78d35906568e
Figma => https://www.figma.com/file/vV9fU8heX2qCHfcrxYGCZB/Commentaire_action_(MiLo)?node-id=12%3A139
=> Feat/ [US-890] Afficher les commentaires d'une action

lib/analytics/analytics_constants.dart, lib/pages/user_action/action_commentaires_page.dart, lib/pages/user_action/user_action_detail_page.dart
Trello 919 => https://trello.com/c/HgnlFr0B/919-us-919-urls-matomo-afficher-les-commentaires-dune-action
Trello 920 => https://trello.com/c/SqI5qR2e/920-us-920-urls-matomo-modifier-les-commentaires-dune-action
=> Feat/ [US 919&920] Add Matomo To Comments

lib/pages/chat_page.dart
Error has been seen several times on production
=> [FIX] Correctif de bug vus en prod

lib/pages/user_action/user_action_detail_page.dart, lib/presentation/user_action/user_action_details_view_model.dart, test/presentation/user_action/user_action_details_view_model_test.dart
Trello => https://trello.com/c/4Sc1gIQJ/948-us-948-emp%C3%AAcher-la-suppression-dune-action-avec-des-commentaires
=> feat(948): Last MR de Lana =)

lib/configuration/configuration.dart, lib/features/deep_link/deep_link_state.dart, lib/pages/main_page.dart, lib/presentation/main_page_view_model.dart, lib/presentation/router_page_view_model.dart, lib/ui/strings.dart, test/doubles/fixtures.dart, test/feature/deep_link/deep_link_test.dart, test/presentation/router_page_view_model_test.dart
Ne pas oublier de rajouter les variables d'environment pour staging et prod
=> Feat (1264) Notification pour actualiser la situation PE

lib/features/rendezvous/list/rendezvous_list_actions.dart, lib/features/rendezvous/list/rendezvous_list_middleware.dart, lib/features/rendezvous/list/rendezvous_list_reducer.dart, lib/features/rendezvous/list/rendezvous_list_state.dart, lib/models/rendezvous_list_result.dart, lib/pages/rendezvous/rendezvous_list_page.dart, lib/presentation/rendezvous/list/rendezvous_list_view_model.dart, lib/repositories/rendezvous/rendezvous_repository.dart, lib/ui/strings.dart, lib/widgets/snack_bar/show_snack_bar.dart, test/assets/rendezvous.json, test/assets/rendezvous_pole_emploi.json, test/assets/rendezvous_where_conseiller_is_createur.json, test/assets/rendezvous_with_unknown_type.json, test/dsl/app_state_dsl.dart, test/feature/rendezvous/rendezvous_list_test.dart, test/presentation/rendezvous/list/rendezvous_list_view_model_test.dart, test/repositories/rendezvous/rendezvous_repository_test.dart
=> [FEAT] 1307 : Jeune PE message d'erreur et retour visuel sur l'onglet rdv

lib/pages/chat_page.dart, lib/pages/favoris/favoris_tabs_page.dart, lib/pages/main_page.dart, lib/pages/mon_suivi_tabs_page.dart, lib/pages/profil/profil_page.dart, lib/pages/solutions_tabs_page.dart, lib/ui/font_sizes.dart, lib/ui/shadows.dart, lib/ui/text_styles.dart, lib/widgets/default_app_bar.dart, lib/widgets/profile_button.dart
=> feat(1346): add primary appBar and mode demo banner

lib/app_initializer.dart, lib/models/details_jeune.dart, lib/repositories/session_milo_repository.dart, test/assets/details_jeune.json, test/doubles/dummies.dart, test/doubles/fixtures.dart, test/repositories/details_jeune_repository_test.dart
On voulait faire un feature flip un peu tricky :
En gros, la possibilité d'activer ou de désactiver les sessions de manière globale.
Et en //, la possibilité de gérer nos early adopter.
J'ai fait le code qui me semblait le plus facile à défaire une fois qu'on aura les sessions dispo pour tous le monde, dites-moi si ça vous va :)
=> feat(274): Add dynamic feature flip on sessions

lib/features/login/login_middleware.dart, lib/utils/pass_emploi_matomo_tracker.dart, pubspec.lock, pubspec.yaml, test/doubles/mocks.dart, test/features/login/login_test.dart, test/features/login/post_logout_sign_out_from_firebase_test.dart, test/features/suppression_compte_test.dart
La nouvelle version de Matomo permet d'avoir de la remontée de tracking même si on n'a pas de réseau.
=> build: Bump Matomo version

lib/analytics/analytics_constants.dart, lib/pages/user_action_form/create_user_action_form.dart, lib/pages/user_action_form/create_user_action_form_page.dart, lib/pages/user_action_form/create_user_action_form_step1_page.dart, lib/pages/user_action_form/create_user_action_form_step2_page.dart, lib/pages/user_action_form/create_user_action_form_step3_page.dart, lib/presentation/user_action/creation_form/create_user_action_form_view_model.dart
J'en ai profité pour corriger 2 ptis trucs sur la feature de base (les 2 premiers commits)
Y'a également un peu de bruit parce qu'initialement je n'avais pas mis mon code de tracking dans le `CreateUserActionForm`, mais j'ai du finalement le déplacer. A ce titre, j'avais renommé quelque param, et ça me semble pas déconnant de laisser ces noms plus explicites.
=> feat(2182): Taggage formulaire création d'action v2

.github/workflows/continuous-integration-workflow.yml, .github/workflows/release-workflow.yml, scripts/generate_env_ci.sh
Il faudra ensuite supprimer sur la CI les 2 champs reliés au P12
=> ci: remove obsolete certificate installation steps in CI

assets/mode_demo/mon_suivi_pole_emploi.json, lib/features/mode_demo/mode_demo_files.dart, lib/features/mon_suivi/mon_suivi_middleware.dart, lib/features/mon_suivi/mon_suivi_state.dart, lib/models/mon_suivi.dart, lib/pages/agenda_page.dart, lib/pages/demarche/create_demarche_step1_page.dart, lib/pages/demarche/demarche_list_page.dart, lib/pages/main_page.dart, lib/pages/mon_suivi_milo_page.dart, lib/pages/mon_suivi_page.dart, lib/presentation/demarche/demarche_state_source.dart, lib/presentation/demarche/demarche_view_model_helper.dart, lib/presentation/main_page_view_model.dart, lib/presentation/mon_suivi/mon_suivi_view_model.dart, lib/redux/app_state.dart, lib/redux/store_factory.dart, lib/repositories/mon_suivi_repository.dart, lib/repositories/remote_config_repository.dart, lib/ui/strings.dart, lib/widgets/cards/demarche_card.dart, test/assets/mon_suivi_pole_emploi.json, test/doubles/fixtures.dart, test/feature/mon_suivi/mon_suivi_test.dart, test/presentation/main_page_view_model_test.dart, test/presentation/mon_suivi/mon_suivi_view_model_test.dart, test/repositories/mon_suivi_repository_test.dart
=> feat(2585):  Refonte de la page Mon suivi pour FT - iso comportement Milo

assets/mode_demo/mon_suivi_pole_emploi.json, lib/features/mon_suivi/mon_suivi_state.dart, lib/models/mon_suivi.dart, lib/pages/agenda_page.dart, lib/pages/mon_suivi_page.dart, lib/presentation/demarche/demarche_card_view_model.dart, lib/presentation/mon_suivi/mon_suivi_view_model.dart, lib/ui/strings.dart, lib/widgets/cards/base_cards/widgets/card_pillule.dart, lib/widgets/cards/demarche_card.dart, lib/widgets/not_up_to_date_message.dart, test/assets/mon_suivi_pole_emploi_date_derniere_maj.json, test/doubles/fixtures.dart, test/presentation/demarche/demarche_card_view_model_test.dart, test/presentation/mon_suivi/mon_suivi_view_model_test.dart, test/repositories/mon_suivi_repository_test.dart
=> feat(mon-suivi-pe): Partie 2

lib/pages/notification_preferences_page.dart, lib/presentation/preferences/notification_preferences_view_model.dart, lib/ui/strings.dart, test/presentation/preferences/notification_preferences_view_model_test.dart
Remove message entry + add A11Y link info
=> feat: Retours PO pages préférences notif
